/**
 * Download the font faces we offer and write a self-hosted stylesheet.
 *
 * Self-hosting is not a preference here, it is a requirement: the renderer
 * measures and draws text into a canvas frame by frame, and a face that
 * arrives late would silently produce a video whose opening seconds are set
 * in the fallback. Bundled files let us await document.fonts.load() once and
 * know we are ready.
 *
 * Only the latin and latin-ext subsets are kept — latin-ext is what carries
 * the accented characters Spanish and Portuguese lyrics need.
 *
 *   npm run fonts
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { FONTS } from '../shared/templates.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(HERE, '..', 'public', 'fonts');

// Google serves woff2 only to user agents it believes support it.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

async function cssFor(family, weights) {
  const spec = `${family.replace(/ /g, '+')}:wght@${weights.join(';')}`;
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=block`;
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) {
    // Single-weight families (Anton, DM Serif Display) reject the wght axis.
    const plain = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, '+')}&display=block`;
    const retry = await fetch(plain, { headers: { 'user-agent': UA } });
    if (!retry.ok) throw new Error(`${family}: ${res.status}`);
    return retry.text();
  }
  return res.text();
}

/** Split the stylesheet into blocks, keeping the /* subset *​/ comment above each. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let match;
  while ((match = re.exec(css))) {
    const [, subset, block] = match;
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() || '400';
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() || 'normal';
    const src = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (src && style === 'normal') faces.push({ subset, weight, src, range });
  }
  return faces;
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const rules = [];
  let downloaded = 0;

  for (const font of FONTS) {
    const css = await cssFor(font.name, font.weights);
    const faces = parseFaces(css).filter((f) => WANTED_SUBSETS.has(f.subset));

    if (!faces.length) {
      console.warn(`  ! ${font.name}: no latin faces found`);
      continue;
    }

    // A variable font serves one file per subset covering every weight; a
    // static family serves one per weight. Dedupe by URL so we never write
    // the same bytes twice under two names.
    const seen = new Map();
    for (const face of faces) {
      let file = seen.get(face.src);
      if (!file) {
        file = `${font.id}-${face.subset}-${face.weight.replace(/\s+/g, '')}.woff2`;
        const res = await fetch(face.src, { headers: { 'user-agent': UA } });
        if (!res.ok) throw new Error(`${font.name} ${face.weight}: ${res.status}`);
        await fs.writeFile(path.join(OUT_DIR, file), Buffer.from(await res.arrayBuffer()));
        seen.set(face.src, file);
        downloaded++;
      }
      rules.push(
        `@font-face{font-family:"${font.name}";font-style:normal;font-weight:${face.weight};` +
        `font-display:block;src:url("/fonts/${file}") format("woff2");` +
        (face.range ? `unicode-range:${face.range};` : '') + '}'
      );
    }
    console.log(`  ✓ ${font.name} (${seen.size} file${seen.size === 1 ? '' : 's'})`);
  }

  const header =
    '/* Generated by scripts/fetch-fonts.mjs — do not edit. */\n' +
    '/* Fonts are SIL Open Font License 1.1; see public/fonts/OFL.txt. */\n';
  await fs.writeFile(path.join(OUT_DIR, 'fonts.css'), header + rules.join('\n') + '\n', 'utf8');

  await fs.writeFile(
    path.join(OUT_DIR, 'OFL.txt'),
    'The typefaces in this directory are distributed under the SIL Open Font\n' +
    'License 1.1, which permits redistribution and embedding, including in\n' +
    'video output. Full text: https://openfontlicense.org\n\n' +
    FONTS.map((f) => `  ${f.name} — https://fonts.google.com/specimen/${f.name.replace(/ /g, '+')}`).join('\n') + '\n',
    'utf8'
  );

  console.log(`\n${downloaded} files -> ${OUT_DIR}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
